import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {WorldStore} from '../server/world-store.mjs';
import {WorldSimulation} from '../src/server/world-simulation.ts';
import {CollisionWorld} from '../src/world/collision-world.ts';
import {TerrainSurface} from '../src/world/terrain-surface.ts';
import {restoreWorldTopology} from '../src/world/world-topology.ts';
import {SERVICES,isTerritorySafe} from '../src/world/territory.ts';
import {worldCycleAt,rollNightDrops,PHASE_MS,CYCLE_MS} from '../src/world/world-cycle.ts';
import {CLASSES} from '../src/data/game-data.ts';
import {findNavigationPath} from '../src/world/navigation.ts';
let serial=0;
test('night loot uses exclusive 1% scroll and 2% jewelry bands',()=>{for(const[a,b,expected]of [[0,0,['weapon_scroll_improved','ember_ring']],[.005,.01,['armor_scroll_improved','fang_necklace']],[.01,.02,[]]]){const rolls=[a,b];assert.deepEqual(rollNightDrops(()=>rolls.shift()),expected);}});
function setup(){const store=new WorldStore(':memory:');const sim=new WorldSimulation({store,collision:new CollisionWorld(),terrain:new TerrainSurface(),now:100000,identifier:()=>`polish-${++serial}`,random:()=>.4});const p=sim.createCharacter('Тест','ranger');Object.assign(p,{x:45,z:-50,activeUntil:1e10});sim.state.monsters.forEach(m=>{m.alive=false;m.respawnAt=1e12});const m=sim.state.monsters[0];Object.assign(m,{id:'undead',x:50,z:-50,home:{x:50,z:-50},alive:true,hp:10000,attackReadyAt:1e12,regionId:undefined});return{sim,store,p,m};}
function run(sim,seconds){for(let i=0;i<Math.ceil(seconds*60);i++)sim.advance(sim.state.time+1000/60+.00001);}
function cmd(sim,p,value,id=`command-${++serial}`){return sim.command(p.id,id,value);}
test('one LMB intention produces exactly one basic attack',()=>{const {sim,store,p,m}=setup();try{sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:null,mode:'single'});run(sim,3.5);assert.equal(sim.events.filter(e=>e.kind==='attack'&&e.actor===p.id).length,1);assert.equal(p.autoAttack,false);assert.ok(m.hp<10000);}finally{store.close();}});
test('latched autoattack survives movement and resumes on release; Escape clears it',()=>{const {sim,store,p,m}=setup();try{sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:null,mode:'auto'});run(sim,1);sim.input(p.id,2,{type:'direction',x:0,z:1});assert.equal(p.target,m.uid);assert.equal(p.autoAttack,true);run(sim,.3);const before=sim.events.filter(e=>e.kind==='attack'&&e.actor===p.id).length;sim.input(p.id,3,{type:'direction',x:0,z:0});run(sim,2);assert.ok(sim.events.filter(e=>e.kind==='attack'&&e.actor===p.id).length>before);sim.input(p.id,4,{type:'cancel'});assert.equal(p.autoAttack,false);assert.equal(p.target,null);}finally{store.close();}});
test('ready skill starts in the input tick and pays once, interrupting a basic attack',()=>{const {sim,store,p,m}=setup();try{sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:null,mode:'auto'});run(sim,.1);const now=sim.state.time,mp=p.mp;sim.input(p.id,2,{type:'attack',entityId:m.uid,skill:0});assert.equal(sim.events.findLast(e=>e.kind==='attack'&&e.actor===p.id).at,now);assert.equal(p.mp,mp-18);assert.equal(sim.events.findLast(e=>e.kind==='release'&&e.actor===p.id&&e.skill===0).at,now);const cooldown=p.cooldowns[0];assert.throws(()=>sim.input(p.id,3,{type:'attack',entityId:m.uid,skill:0}),/cooldown/);run(sim,.4);assert.equal(p.cooldowns[0],cooldown);assert.ok(m.hp<10000);}finally{store.close();}});
test('provocation explicitly acquires attacker outside ordinary aggro radius',()=>{const {sim,store,p,m}=setup();try{m.x=p.x+12;m.home.x=m.x;m.attackReadyAt=0;sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:0});assert.equal(m.provokedBy,p.id);run(sim,.2);assert.equal(m.targetId,p.id);assert.equal(m.action,'walk');}finally{store.close();}});
test('provoked attack interval is base interval divided by 1.25',()=>{const {sim,store,p,m}=setup();try{m.x=p.x+1.5;m.home.x=m.x;m.attackReadyAt=0;sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:0});const now=sim.state.time;run(sim,.02);assert.ok(Math.abs(m.attackReadyAt-now-(2050/1.25+1000/60))<1); }finally{store.close();}});
test('haste purchased at either alchemist: exact 50% run, expiry and no stacking',()=>{const {sim,store,p}=setup();try{const base=p.stats.speed;for(const id of ['npc:alchemist','npc:asterhold:alchemist']){Object.assign(p,SERVICES[id]);assert.equal(cmd(sim,p,{type:'buy',itemId:'haste'}).ok,true);const item=p.inventory.find(i=>i.id==='haste');assert.equal(cmd(sim,p,{type:'use',item:{...item}}).ok,true);assert.equal(p.stats.speed,base*1.5);}const expiry=p.buffs.haste;p.activeUntil=0;sim.advance(expiry+1000);assert.equal(p.stats.speed,base);assert.equal(p.buffs.haste,0);}finally{store.close();}});
test('500th warehouse slot survives restart and withdrawal in the second town without duplicating UID',()=>{const {sim,store,p}=setup();try{Object.assign(p,SERVICES['npc:storage']);const item={...p.inventory[0]},command={type:'storage',direction:'deposit',item,index:499};assert.equal(cmd(sim,p,command,'storage-receipt-001').ok,true);assert.equal(cmd(sim,p,command,'storage-receipt-001').ok,true);assert.equal(p.storage[499].uid,item.uid);assert.ok(!p.inventory.some(i=>i.uid===item.uid));const next=new WorldSimulation({store,collision:new CollisionWorld(),now:sim.state.time,identifier:()=>`polish-${++serial}`});const after=next.state.characters[p.id];Object.assign(after,SERVICES['npc:asterhold:storage']);assert.equal(cmd(next,after,{type:'storage',direction:'withdraw',item}).ok,true);assert.equal(after.inventory.filter(i=>i.uid===item.uid).length,1);assert.equal(after.storage[499],null);}finally{store.close();}});
test('warehouse rejects full transfers without changing owned items',()=>{const {sim,store,p}=setup();try{Object.assign(p,SERVICES['npc:storage']);const item={...p.inventory[0]};p.storage=Array.from({length:500},(_,i)=>({...item,uid:`stored-${i}`}));const before=JSON.stringify([p.inventory,p.storage]);assert.equal(cmd(sim,p,{type:'storage',direction:'deposit',item}).reason,'storage-full');assert.equal(JSON.stringify([sim.state.characters[p.id].inventory,sim.state.characters[p.id].storage]),before);}finally{store.close();}});
test('world and trade chat are server shared, identity comes from session and retry is idempotent',()=>{const {sim,store,p}=setup();try{const other=sim.createCharacter('Другой','knight');const c={type:'chat',channel:'world',text:'Привет <мир> [color=red]'};assert.equal(cmd(sim,p,c,'chat-receipt-0001').ok,true);cmd(sim,p,c,'chat-receipt-0001');assert.equal(sim.snapshot(other.id).chat.length,1);assert.equal(sim.snapshot(other.id).chat[0].name,'Тест');assert.equal(cmd(sim,p,{type:'chat',channel:'system',text:'подделка'}).ok,false);}finally{store.close();}});
test('three-hour phases, fourth full moon and persisted independent epoch',()=>{assert.equal(worldCycleAt(PHASE_MS-1,0).night,false);assert.equal(worldCycleAt(PHASE_MS,0).night,true);assert.equal(worldCycleAt(CYCLE_MS,0).night,false);assert.equal(worldCycleAt(CYCLE_MS*3+PHASE_MS,0).fullMoon,true);const {sim,store}=setup();try{const epoch=sim.state.cycleEpoch;sim.checkpoint();const next=new WorldSimulation({store,collision:new CollisionWorld(),now:sim.state.time+8000,identifier:()=>`polish-${++serial}`});assert.equal(next.state.cycleEpoch,epoch);}finally{store.close();}});
test('full moon pairs share target; dawn removes all event monsters and gives no despawn loot',()=>{const {sim,store,p}=setup();try{p.activeUntil=0;let seed=17;sim.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};sim.state.cycleEpoch=sim.state.time-(CYCLE_MS*3+PHASE_MS);run(sim,.05);const night=sim.state.monsters.filter(m=>m.nightIndex!==undefined);assert.equal(night.length,16);assert.equal(new Set(night.map(m=>m.pairId)).size,8);const pair=night.slice(0,2);Object.assign(p,{x:pair[0].x+5,z:pair[0].z,activeUntil:1e10});sim.input(p.id,1,{type:'attack',entityId:pair[0].uid,skill:0});assert.ok(pair.every(m=>m.targetId===p.id));const gold=p.gold;p.activeUntil=0;sim.advance(sim.state.cycleEpoch+CYCLE_MS*4+1);assert.equal(sim.state.monsters.filter(m=>m.nightIndex!==undefined).length,0);assert.equal(p.gold,gold);}finally{store.close();}});
test('dead body has an exact three second visibility deadline',()=>{const {sim,store,p,m}=setup();try{m.hp=1;sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:0});run(sim,.5);assert.equal(m.alive,false);assert.equal(m.corpseUntil-m.deathAt,3000);}finally{store.close();}});
test('all twelve service anchors have reachable free approaches inside their city',()=>{const w=restoreWorldTopology(JSON.parse(readFileSync('public/assets/world/world-topology.json')));assert.equal(Object.keys(SERVICES).length,12);for(const[id,p]of Object.entries(SERVICES)){assert.equal(w.collision.isBlocked(p,.5),false,id);assert.equal(isTerritorySafe(p),true,id);const from=id.includes('asterhold')?{x:-98,z:-84}:{x:12,z:-9};assert.ok(findNavigationPath(w.collision,from,p).length>0,id);}});

test('two ready skills in one server tick both release and pay once',()=>{const {sim,store,p,m}=setup();try{const mp=p.mp,now=sim.state.time;sim.input(p.id,1,{type:'attack',entityId:m.uid,skill:0});sim.input(p.id,2,{type:'attack',entityId:m.uid,skill:1});const releases=sim.events.filter(e=>e.kind==='release'&&e.actor===p.id);assert.deepEqual(releases.map(e=>e.skill),[0,1]);assert.ok(releases.every(e=>e.at===now));assert.equal(p.mp,mp-CLASSES.ranger.skills[0].cost-CLASSES.ranger.skills[1].cost);}finally{store.close();}});
