import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { WorldSimulation, WORLD_PHYSICS_HZ } from '../src/server/world-simulation.ts';
import { MonsterAiBrain } from '../src/world/monster-ai.ts';
import { CollisionWorld } from '../src/world/collision-world.ts';
import { TerrainSurface } from '../src/world/terrain-surface.ts';
import { combatSpacing, approachPoint, attackTimings } from '../src/combat/combat-approach.ts';

// Generated by executing only the pinned, user-approved browser source. The
// fixture records source hashes; no current server/native module generates it.
const golden=JSON.parse(readFileSync(new URL('../godot-pc/tests/reference-control-traces.json',import.meta.url),'utf8'));
const close=(actual,expected,label)=>assert.ok(Math.abs(actual-expected)<1e-8,`${label}: ${actual} != ${expected}`);
function fixture(classId='knight') {
  let sequence=0;const terrain=new TerrainSurface();terrain.heights.fill(0);
  const world=new WorldSimulation({store:{load:()=>null,save:()=>{}},collision:new CollisionWorld(),terrain,now:1000,identifier:()=>`golden-${++sequence}`,random:()=>.5});
  const player=world.createCharacter('Reference',classId);Object.assign(player,{x:40,z:40,yaw:0,hp:99999,maxHp:99999});
  world.heartbeat(player.id);const monsters=world.state.monsters;world.state.monsters=[];
  return {world,player,monsters,input:intent=>world.input(player.id,++sequence,intent)};
}

test('server uses the accepted 60 Hz physics rate and never steps partial HTTP intervals',()=>{
  const {world,player,input}=fixture();assert.equal(WORLD_PHYSICS_HZ,golden.simulation.rate_hz);
  input({type:'direction',x:0,z:1});world.advance(1008);assert.equal(player.z,40);assert.equal(world.state.time,1000);
  world.advance(1016);assert.equal(player.z,40);
  world.advance(1017);close(world.state.time,1000+1000/60,'first full tick');assert.ok(player.z>40);
  const at=player.z;world.advance(1020);assert.equal(player.z,at,'remainder is retained instead of a short step');
});

for(const trace of golden.movement.traces)test(`authoritative physics matches browser trace: ${trace.name}`,()=>{
  const {world,player,input}=fixture();let tick=0;
  for(const segment of trace.segments)for(let i=0;i<segment.ticks;i++,tick++){
    if(i===0||tick%6===0)input({type:'direction',...segment.direction});
    if(trace.jump_ticks.includes(tick)||trace.air_jump_attempt_ticks.includes(tick))input({type:'jump'});
    world.heartbeat(player.id);world.advance(1000+(tick+1)*1000/60);
    const expected=trace.rows[tick];
    close(player.x-40,expected[1],`tick ${tick} x`);close(player.z-40,expected[2],`tick ${tick} z`);
    close(player.yOffset,expected[3],`tick ${tick} jump`);assert.equal(player.grounded,expected[6]);
    close(player.yaw,expected[8],`tick ${tick} facing`);
  }
});

test('30, 60 and 144 Hz delivery produce identical authoritative movement on fixed reference ticks',()=>{
  const positions=[];
  for(const rate of [30,60,144]){
    const {world,player,input}=fixture();input({type:'direction',x:1,z:1});
    for(let frame=1;frame<=rate;frame++){
      if(frame%Math.max(1,Math.round(rate/10))===0)input({type:'direction',x:1,z:1});
      world.heartbeat(player.id);world.advance(1000+frame*1000/rate);
    }
    positions.push([player.x,player.z]);
  }
  for(const value of positions)assert.deepEqual(value,positions[0]);
});

test('twenty server jumps land on the same reference tick and reject every airborne press',()=>{
  const {world,player,input}=fixture();
  for(const expected of golden.movement.repeated_jumps){
    input({type:'jump'});let ticks=0,peak=0;
    do {
      const oldVelocity=player.verticalVelocity;input({type:'jump'});assert.equal(player.verticalVelocity,oldVelocity,'air press cannot reset impulse');
      world.heartbeat(player.id);world.advance(world.state.time+1000/60);ticks++;
      peak=Math.max(peak,player.yOffset);assert.ok(ticks<90);
    }while(!player.grounded);
    assert.equal(ticks,expected.ticks);close(peak,expected.peak,'reference jump peak');
  }
});

test('approach uses reference 78% route goal and 90% settling edge without extending hit range',()=>{
  for(const cls of golden.classes){
    const spacing=combatSpacing(cls.range,.46,.46);
    close(spacing.stoppingDistance,cls.range*.9,`${cls.id} stop edge`);
    close(spacing.destinationDistance,cls.range*.78,`${cls.id} route goal`);
    const point=approachPoint({x:0,z:0},{x:0,z:30},spacing.destinationDistance);
    close(point.z,30-cls.range*.78,`${cls.id} approach position`);
    assert.ok(spacing.destinationDistance>spacing.contact);
  }
});

test('all class attack contacts and recovery retain timings measured by the reference rigs',()=>{
  for(const trace of golden.attacks){
    const cls=golden.classes.find(cls=>cls.id===trace.class_id);
    const timing=attackTimings(cls?.model??'Fox',cls?cls.interval*.92:Infinity);
    close(timing.windup/1000,trace.timings.windup,`${trace.class_id} windup`);
    close((timing.duration-timing.windup)/1000,trace.timings.recovery,`${trace.class_id} recovery`);
  }
});

test('large Fox approach crosses the reference stop edge without getting stranded at its body boundary',()=>{
  for(const classId of ['knight','assassin']){
    const {world,player,monsters,input}=fixture(classId),monster=monsters.find(m=>m.id==='mini');
    Object.assign(monster,{x:40,z:46,home:{x:40,z:46},regionId:undefined,hp:99999});monster.status.stun=1e9;world.state.monsters=[monster];
    input({type:'attack',entityId:monster.uid,skill:null});
    for(let tick=1;tick<=240;tick++){
      world.heartbeat(player.id);world.advance(1000+tick*1000/60);
      assert.ok(Math.hypot(player.x-monster.x,player.z-monster.z)>=2.51-1e-6,'swept body contact is never penetrated');
    }
    assert.ok(world.events.some(event=>event.kind==='hit'&&event.actor===player.id),'navigation cannot stall just outside range');
  }
});

for(const trace of golden.monster_ai.traces)test(`monster AI follows pinned browser decisions: ${trace.name}`,()=>{
  const brain=new MonsterAiBrain(trace.seed);
  if(trace.uses_reset)brain.reset(trace.seed);
  for(const row of trace.rows){
    const decision=brain.update({...trace.defaults,atPatrolPoint:row[1]});
    assert.deepEqual([decision.state,decision.intent,decision.changed],row.slice(2),`tick ${row[0]}`);
  }
});

test('aggro, attack edge and committed return follow the accepted browser sequence',()=>{
  const brain=new MonsterAiBrain(4);
  for(const step of golden.monster_ai.engagement_and_return){
    const decision=brain.update(step.input);
    assert.deepEqual({state:decision.state,intent:decision.intent,changed:decision.changed},step.expected);
  }
});

test('reference corpse deadline keeps death guards and emits exactly one reward',()=>{
  const {world,player,monsters,input}=fixture('ranger');const monster=monsters.find(m=>m.id==='wolf');
  Object.assign(monster,{x:40,z:48,home:{x:40,z:48},regionId:undefined,hp:1});monster.status.stun=1e9;world.state.monsters=[monster];
  input({type:'attack',entityId:monster.uid,skill:null});
  for(let tick=1;monster.alive&&tick<120;tick++)world.advance(1000+tick*1000/60);
  assert.equal(monster.alive,false);assert.equal(monster.combatState,'dead');assert.equal(player.target,null);
  close(monster.corpseUntil-monster.deathAt,1070,'browser .42 death + .65 corpse');
  const at={x:monster.x,z:monster.z};world.advance(monster.deathAt+650);
  assert.equal(world.snapshot(player.id).monsters[0].aiState,'corpse');assert.deepEqual({x:monster.x,z:monster.z},at);
  world.advance(monster.corpseUntil+1000/60);assert.equal(world.snapshot(player.id).monsters[0].aiState,'despawn');
  assert.equal(world.events.filter(event=>event.kind==='loot').length,1);
  assert.equal(world.state.pending.some(attack=>attack.actor===monster.uid||attack.target===monster.uid),false);
});
