import './styles.css';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import * as SkeletonUtils from 'three/addons/utils/SkeletonUtils.js';
import { CLASSES, ITEMS, MONSTERS, ENHANCE, EQUIP_SLOTS, SLOT_NAMES, LOCATIONS } from './data.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a), rint=(a,b)=>Math.floor(rand(a,b+1));
const CHAR_DIR='/assets/models/characters/', MON_DIR='/assets/models/monsters/', WORLD_DIR='/assets/models/world/';
const SAVE_KEY='varendor_reborn_v02';
const state={started:false,paused:false,selectedClass:'knight',target:null,moveTarget:null,entities:[],effects:[],mixers:[],assets:{characters:{},monsters:{},world:{}},worldTime:19.35,selectedItem:null,quest:0,kills:0,bossKills:0,lootBuffer:[],gateWarn:0,settings:{quality:'high',shadows:true,bloom:true,damage:true,screenShake:true,music:.3,sfx:.75,ui:.7},bossTimers:{mini:0,big:0}};
let player={name:'Странник',classId:'knight',level:1,xp:0,gold:320,x:0,z:0,hp:1,mp:1,maxHp:1,maxMp:1,stats:{},inventory:[],equipment:{},cooldowns:[0,0,0,0],attackCd:0,dead:false};
let audioCtx=null,ambientGain=null;
const app=$('#app');

app.innerHTML=`
<canvas id="game-canvas" tabindex="0"></canvas><div class="vignette"></div><div class="grain"></div>
<div class="loading hidden" id="loading"><div class="loading-box"><h1>VARENDOR</h1><div class="loadbar"><i id="load-fill"></i></div><p id="load-text">Пробуждаем древний мир…</p></div></div>
<div class="start-screen" id="start-screen"><div class="start-content"><h1 class="logo">VARENDOR<span>ASHEN FRONTIER</span></h1><div class="eyebrow">Выберите судьбу</div><div class="class-picker" id="class-picker"></div><div class="start-actions"><input class="name-field" id="name-field" maxlength="16" value="Странник" aria-label="Имя персонажа"><button class="gold-btn" id="begin">ВОЙТИ В МИР</button><button class="dark-btn hidden" id="continue">ПРОДОЛЖИТЬ</button></div></div></div>
<div class="hud hidden" id="hud">
 <section class="player-frame glass"><div class="portrait" id="portrait">V</div><div><div class="identity"><b id="player-name">Странник</b><span id="player-class">ур. 1</span><span class="coins">◈ <i id="gold">0</i></span></div><div class="bar"><i id="hp-fill"></i><span id="hp-text"></span></div><div class="bar mana"><i id="mp-fill"></i><span id="mp-text"></span></div><div class="bar xp"><i id="xp-fill"></i></div></div></section>
 <section class="target-frame glass hidden" id="target-frame"><div><span class="boss-mark" id="boss-mark"></span><span class="target-name" id="target-name"></span><span class="target-meta" id="target-meta"></span></div><div class="bar"><i id="target-fill"></i><span id="target-hp"></span></div></section>
 <section class="minimap-wrap glass"><canvas class="minimap" id="minimap" width="428" height="328"></canvas><span class="clock" id="clock">19:21</span><div class="zone" id="zone">Гринфолл</div></section>
 <section class="tracker glass"><div class="eyebrow">Путь странника</div><h3 id="quest-title">Голос границы</h3><p id="quest-text">Поговорите со старостой Гринфолла.</p><div class="progress"><i id="quest-progress"></i></div></section>
 <section class="boss-timers glass"><div class="eyebrow">Владыки региона</div><div class="timer"><span>Кровавый Оборотень</span><b id="mini-timer">жив</b></div><div class="timer"><span>Хозяин Гнилого Леса</span><b id="big-timer">жив</b></div></section>
 <section class="combat-log glass"><div class="messages" id="messages"></div><div class="chat-input"><input id="chat" placeholder="Enter — общий чат"><button id="send-chat">›</button></div></section>
 <div class="bottom-cluster"><div class="hotbar glass" id="hotbar"></div><nav class="menu glass"><button class="menu-button" data-window="character"><span>C</span><small>Герой</small></button><button class="menu-button" data-window="inventory"><span>I</span><small>Сумка</small></button><button class="menu-button" data-window="skills"><span>K</span><small>Навыки</small></button><button class="menu-button" data-window="map"><span>M</span><small>Карта</small></button><button class="menu-button" data-window="settings"><span>Esc</span><small>Настройки</small></button></nav></div>
 <div class="quick-items glass"><button class="skill-button" id="potion"><span class="key">Q</span><span class="symbol">♥</span><small>Зелье <b id="potion-count">0</b></small></button><button class="skill-button" id="ether"><span class="key">E</span><span class="symbol">◆</span><small>Эфир <b id="ether-count">0</b></small></button></div>
 <div class="notice-stack" id="notices"></div><div class="damage-layer" id="damage-layer"></div>
</div><div id="modal-root"></div><div id="confirm-root"></div>`;

Object.entries(CLASSES).forEach(([id,c])=>{$('#class-picker').insertAdjacentHTML('beforeend',`<button class="class-option ${id==='knight'?'selected':''}" data-class="${id}"><span class="class-symbol" style="color:#${c.color.toString(16).padStart(6,'0')}">${c.skills[0].icon}</span><b>${c.name}</b><small>${c.title}<br>HP ${c.hp} · ${c.resource} ${c.mp}</small></button>`)});
$$('[data-class]').forEach(b=>b.onclick=()=>{$$('[data-class]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selectedClass=b.dataset.class});
if(localStorage.getItem(SAVE_KEY))$('#continue').classList.remove('hidden');

const canvas=$('#game-canvas'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x091014);scene.fog=new THREE.FogExp2(0x0b1416,.018);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,190);camera.position.set(14,17,16);camera.lookAt(0,0,0);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.42,.55,.82);composer.addPass(bloom);composer.addPass(new OutputPass());
const clock3=new THREE.Clock(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),glLoader=new GLTFLoader(),fbxLoader=new FBXLoader();
const groundGroup=new THREE.Group(),worldGroup=new THREE.Group(),entityGroup=new THREE.Group(),fxGroup=new THREE.Group();scene.add(groundGroup,worldGroup,entityGroup,fxGroup);
const hemi=new THREE.HemisphereLight(0x7999b8,0x1f1611,1.25);scene.add(hemi);const moon=new THREE.DirectionalLight(0x9ac5e3,2.2);moon.position.set(-20,34,-12);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-55;moon.shadow.camera.right=55;moon.shadow.camera.top=55;moon.shadow.camera.bottom=-55;scene.add(moon);
const groundMat=new THREE.MeshStandardMaterial({color:0x263229,roughness:.98,metalness:.02});const ground=new THREE.Mesh(new THREE.PlaneGeometry(105,90,55,45),groundMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.name='ground';const pos=ground.geometry.attributes.position;for(let i=0;i<pos.count;i++){let x=pos.getX(i),y=pos.getY(i);pos.setZ(i,(Math.sin(x*.37)+Math.cos(y*.29)+Math.sin((x+y)*.17))*.13)}ground.geometry.computeVertexNormals();groundGroup.add(ground);
const roadMat=new THREE.MeshStandardMaterial({color:0x5b5140,roughness:1});function road(x,z,w,d,r=0){let m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),roadMat);m.rotation.set(-Math.PI/2,0,r);m.position.set(x,.035,z);m.receiveShadow=true;groundGroup.add(m)}road(-15,-9,35,4,.12);road(7,1,31,3.8,-.25);road(28,15,35,3.2,-.43);
const safeRing=new THREE.Mesh(new THREE.RingGeometry(7.7,7.85,80),new THREE.MeshBasicMaterial({color:0xd4b66a,transparent:true,opacity:.32,side:THREE.DoubleSide}));safeRing.rotation.x=-Math.PI/2;safeRing.position.set(-8,.08,-5);scene.add(safeRing);

function xpNeed(l=player.level){return Math.floor(145*Math.pow(l,1.78))}function makeItem(id,plus=0,count=1){return{id,plus,count,uid:crypto.randomUUID?.()||Date.now()+Math.random()}}function itemDef(o){return ITEMS[o.id]}
function newPlayer(){let c=CLASSES[state.selectedClass];player={name:$('#name-field').value.trim()||'Странник',classId:state.selectedClass,level:1,xp:0,gold:320,x:-7,z:-4,hp:1,mp:1,maxHp:1,maxMp:1,stats:{},inventory:[makeItem('potion',0,6),makeItem('ether',0,4),makeItem('scroll',0,4),makeItem('teleport',0,1)],equipment:{weapon:makeItem(c.weapon),chest:makeItem(c.armor)},cooldowns:[0,0,0,0],attackCd:0,dead:false};state.quest=0;state.kills=0;state.bossKills=0;recalc(true)}
function recalc(fill=false){let c=CLASSES[player.classId],s={...c.stats},b={atkMin:s.str*2+player.level*1.5,atkMax:s.str*2.7+player.level*2,matk:s.int*2.6+player.level*1.8,def:s.vit*1.2+player.level*.7,mdef:s.spi*1.15+player.level*.65,crit:4+s.dex*.55,accuracy:78+s.dex*.7,evasion:s.dex*.45,speed:6.2,hp:0,mp:0};Object.values(player.equipment).filter(Boolean).forEach(o=>{let d=itemDef(o),mul=1+o.plus*.14;if(d.atk){b.atkMin+=d.atk[0]*mul;b.atkMax+=d.atk[1]*mul}for(let k of ['matk','def','mdef'])b[k]+=(d[k]||0)*mul;for(let k of ['crit','accuracy','evasion','speed','hp','mp'])b[k]+=d[k]||0});player.stats={...s,...b};player.maxHp=Math.round(c.hp+player.level*(player.classId==='knight'?28:17)+s.vit*7+b.hp);player.maxMp=Math.round(c.mp+player.level*(c.ranged?14:9)+s.spi*5+b.mp);if(fill){player.hp=player.maxHp;player.mp=player.maxMp}else{player.hp=Math.min(player.hp,player.maxHp);player.mp=Math.min(player.mp,player.maxMp)}updateHUD()}

function loadGLTF(url){return new Promise((res,rej)=>glLoader.load(url,g=>res(g),undefined,rej))}function loadFBX(url){return new Promise((res,rej)=>fbxLoader.load(url,res,undefined,rej))}
async function loadAssets(){const tasks=[];let done=0,total=5+4+18;const progress=t=>{$('#load-fill').style.width=`${Math.round(++done/total*100)}%`;$('#load-text').textContent=t};for(const c of Object.values(CLASSES)){tasks.push(loadGLTF(`${CHAR_DIR}${c.model}.gltf`).then(g=>{state.assets.characters[c.model]=g;progress(`Вооружаем: ${c.name}`)}))}for(const m of ['Skeleton','Slime','Bat','Dragon'])tasks.push(loadFBX(`${MON_DIR}${m}.fbx`).then(g=>{state.assets.monsters[m]=g;progress(`Пробуждаем: ${m}`)}));let worldNames=['tree','tree-crooked','tree-high','tree-high-crooked','rock-large','rock-wide','lantern','fence','fence-broken','cart','stall','stall-red','wall-arch','wall-block','wall-corner','wall-door','roof-high','fountain-round'];for(let n of worldNames)tasks.push(loadGLTF(`${WORLD_DIR}${n}.glb`).then(g=>{state.assets.world[n]=g.scene;progress('Возводим Астерхолд')}));await Promise.all(tasks)}
function prepObject(root,tint){root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material=o.material.clone();if(tint&&o.material.color)o.material.color.multiply(new THREE.Color(tint));o.material.roughness=.78}}});return root}
function cloneAnimated(asset,scale=1,tint){let root=SkeletonUtils.clone(asset.scene||asset);prepObject(root,tint);root.scale.setScalar(scale);let clips=asset.animations||[];return{root,clips}}
function pickClip(clips,type){let terms={idle:['idle','survey'],walk:['walk','run','flying'],attack:['sword_attack','dagger_attack','bow_shoot','attack','spell','shoot','cast'],death:['death','die']}[type]||[type];for(let t of terms){let found=clips.find(c=>c.name.toLowerCase().includes(t));if(found)return found}return clips[type==='attack'?1:0]}
function setAction(e,type,once=false){if(!e.mixer||!e.clips.length)return;let clip=pickClip(e.clips,type);if(!clip||e.actionType===type&&!once)return;let next=e.mixer.clipAction(clip);next.reset();next.enabled=true;next.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat);next.clampWhenFinished=once;next.fadeIn(.14).play();if(e.action&&e.action!==next)e.action.fadeOut(.12);e.action=next;e.actionType=type}
function addEntityModel(e,kind){let source=kind==='player'||kind==='npc'?state.assets.characters[e.model]:state.assets.monsters[e.model];let obj=cloneAnimated(source,e.scale||.01,e.tint);e.mesh=obj.root;e.clips=obj.clips;e.mesh.position.set(e.x,0,e.z);e.mesh.userData.entity=e;e.mesh.traverse(o=>o.userData.entity=e);entityGroup.add(e.mesh);e.mixer=new THREE.AnimationMixer(e.mesh);state.mixers.push(e.mixer);setAction(e,'idle');if(kind==='monster')addNameplate(e);if(kind==='npc')addNpcLabel(e)}
function addNpcLabel(e){let c=document.createElement('canvas');c.width=512;c.height=80;let x=c.getContext('2d');x.textAlign='center';x.shadowColor='#000';x.shadowBlur=9;x.font='700 25px Inter';x.fillStyle='#e1c17f';x.fillText(e.name,256,31);x.font='18px Inter';x.fillStyle='#b9afa0';x.fillText({elder:'Задание',smith:'Кузница',shop:'Торговля',teleport:'Переход'}[e.role],256,59);let tex=new THREE.CanvasTexture(c),s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));s.scale.set(5.4,.84,1);s.position.y=3.4;s.renderOrder=20;e.mesh.add(s)}
function addNameplate(e){let c=document.createElement('canvas');c.width=512;c.height=96;let x=c.getContext('2d');x.font=`700 ${e.boss?29:25}px Inter`;x.textAlign='center';x.fillStyle=e.boss?'#efb4a0':'#e8e0d0';x.shadowColor='#000';x.shadowBlur=8;x.fillText(e.name,256,35);x.fillStyle='#090b0c';x.fillRect(96,56,320,14);x.fillStyle=e.boss?'#b63339':'#7f242b';x.fillRect(99,59,314,8);let tex=new THREE.CanvasTexture(c);let s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));s.scale.set(e.boss?7:5.5,e.boss?1.32:1.05,1);s.position.y=e.boss?5.5:3.4;s.renderOrder=20;e.mesh.add(s);e.nameSprite=s;e.nameCanvas=c;e.nameCtx=x}
function refreshNameplate(e){if(!e.nameCtx)return;let x=e.nameCtx;x.clearRect(0,0,512,96);x.font=`700 ${e.boss?29:25}px Inter`;x.textAlign='center';x.fillStyle=e.boss?'#efb4a0':'#e8e0d0';x.shadowColor='#000';x.shadowBlur=8;x.fillText(e.name,256,35);x.fillStyle='#090b0c';x.fillRect(96,56,320,14);x.fillStyle=e.boss?'#b63339':'#7f242b';x.fillRect(99,59,314*clamp(e.hp/e.maxHp,0,1),8);e.nameSprite.material.map.needsUpdate=true}

function worldModel(name,x,z,s=1,rot=0,tint){let src=state.assets.world[name];if(!src)return;let o=src.clone(true);prepObject(o,tint);o.position.set(x,0,z);o.rotation.y=rot;o.scale.setScalar(s);worldGroup.add(o);return o}
function buildWorld(){worldGroup.clear();for(let i=0;i<65;i++){let forest=i>28,x=forest?rand(12,47):rand(-43,25),z=forest?rand(5,36):rand(-31,19);if(Math.hypot(x+8,z+5)<10)continue;worldModel(['tree','tree-crooked','tree-high','tree-high-crooked'][i%4],x,z,rand(1.1,2.2),rand(0,6.28),forest?0x879b83:0x9aa38c)}for(let i=0;i<28;i++)worldModel(i%2?'rock-large':'rock-wide',rand(-46,48),rand(-35,37),rand(.7,1.7),rand(0,6.28),0x8b918b);buildTown(-27,-19,1.5);buildTown(-7,-5,1);for(let i=0;i<8;i++)worldModel(i%3?'fence':'fence-broken',-14+i*2.2,-7+i*.22,1,0);for(let p of [[-10,-4],[-4,-7],[-25,-16],[-30,-22],[19,7],[35,25]]){let l=worldModel('lantern',p[0],p[1],1.4);if(l){let light=new THREE.PointLight(0xff8b35,5.5,10,2);light.position.set(0,2.6,0);l.add(light)}}let mine=worldModel('wall-arch',39,31,3.2,Math.PI,0x59605d);for(let i=0;i<6;i++)worldModel('rock-large',35+rand(0,8),27+rand(0,8),rand(1.5,2.4),rand(0,6.28),0x5f615d)}
function buildTown(x,z,s){for(let i=0;i<7;i++){let a=i/7*Math.PI*2,r=5*s;worldModel('wall-block',x+Math.cos(a)*r,z+Math.sin(a)*r,1.5*s,-a,0xb0a999)}worldModel('wall-arch',x,z+5*s,1.8*s,0,0xb0a999);worldModel('roof-high',x-2*s,z-1*s,2*s,.2,0x8c6c61);worldModel('roof',x+2.5*s,z-1.4*s,1.7*s,-.2,0x79524a);worldModel('fountain-round',x,z,1.5*s);worldModel('stall-red',x+3*s,z+2*s,1.2*s,-1);worldModel('cart',x-3*s,z+1.5*s,1.1*s,.5)}
function spawnEntities(){state.entities.forEach(e=>e.mesh&&entityGroup.remove(e.mesh));state.entities=[];state.mixers=[];let c=CLASSES[player.classId];state.playerEntity={kind:'player',model:c.model,scale:.72,x:player.x,z:player.z,tint:0xffffff};addEntityModel(state.playerEntity,'player');let npcs=[['Староста Роэн','Warrior',-7,-2.5,'elder'],['Кузнец Бран','Warrior',-10,-6,'smith'],['Торговка Эльза','Ranger',-4.8,-5,'shop'],['Проводник Каэль','Wizard',-7.5,-8,'teleport']];npcs.forEach(([name,model,x,z,role])=>{let e={kind:'npc',name,model,x,z,role,scale:.7,tint:role==='smith'?0xc9875c:0xffffff};addEntityModel(e,'npc');state.entities.push(e)});let types=['wolf','exile','spider','undead','bat','cultist','miner','wraith'];for(let i=0;i<36;i++){let forest=i>=17,x=forest?rand(13,34):rand(1,17),z=forest?rand(4,24):rand(-2,15);spawnMonster(types[i%types.length],x,z)}spawnMonster('mini',26,5);spawnMonster('big',39,32)}
function spawnMonster(id,x,z,delay=0){let d=MONSTERS[id],e={kind:'monster',id,name:d.name,model:d.model,level:d.level,boss:d.boss,hp:d.hp,maxHp:d.hp,atk:d.atk,baseAtk:d.atk,phase:1,x,z,homeX:x,homeZ:z,scale:d.scale*.01,tint:d.tint,alive:delay<=0,respawn:delay,attackCd:rand(0,1),hitFlash:0,status:{}};addEntityModel(e,'monster');e.mesh.visible=e.alive;state.entities.push(e);return e}

async function startGame(load=false){initAudio();$('#start-screen').classList.add('hidden');$('#loading').classList.remove('hidden');if(load){try{let s=JSON.parse(localStorage.getItem(SAVE_KEY));player=s.player;state.quest=s.quest||0;state.kills=s.kills||0;state.bossKills=s.bossKills||0;state.lootBuffer=s.lootBuffer||[];state.settings={...state.settings,...s.settings};state.selectedClass=player.classId}catch{newPlayer()}}else newPlayer();await loadAssets();buildWorld();spawnEntities();applySettings();$('#loading').classList.add('hidden');$('#hud').classList.remove('hidden');state.started=true;buildHotbar();updateQuest();recalc(load?false:true);log(`Добро пожаловать в Варендор, ${player.name}.`,'system');log('ЛКМ — путь и цель. Space — атака. 1–4 — навыки.','system');canvas.focus();saveGame()}
$('#begin').onclick=()=>startGame(false);$('#continue').onclick=()=>startGame(true);

function buildHotbar(){let c=CLASSES[player.classId],h=$('#hotbar');h.innerHTML='';c.skills.forEach((s,i)=>h.insertAdjacentHTML('beforeend',`<button class="skill-button" data-skill="${i}"><span class="key">${i+1}</span><span class="symbol">${s.icon}</span><small>${s.name}</small><i class="cooldown"></i></button>`));h.insertAdjacentHTML('beforeend','<button class="skill-button" data-attack><span class="key">Space</span><span class="symbol">⚔</span><small>Обычная атака</small></button>');$$('[data-skill]').forEach(b=>b.onclick=()=>castSkill(+b.dataset.skill));$('[data-attack]').onclick=basicAttack}
function zoneAt(x,z){if(Math.hypot(x+27,z+19)<9)return LOCATIONS[0];if(Math.hypot(x+7,z+5)<7.8)return LOCATIONS[1];if(x>32&&z>24)return LOCATIONS[4];if(x>13)return LOCATIONS[3];return LOCATIONS[2]}
function update(dt){if(!state.started||state.paused)return;state.worldTime=(state.worldTime+dt*.035)%24;state.gateWarn=Math.max(0,state.gateWarn-dt);let pe=state.playerEntity;if(state.moveTarget){let dx=state.moveTarget.x-player.x,dz=state.moveTarget.z-player.z,d=Math.hypot(dx,dz);if(d<.18){state.moveTarget=null;setAction(pe,'idle')}else{let sp=player.stats.speed;player.x+=dx/d*sp*dt;player.z+=dz/d*sp*dt;if(player.x>13&&player.level<10){player.x=12.9;state.moveTarget=null;if(!state.gateWarn){toast('Чёрный лес откроется на 10 уровне','bad');state.gateWarn=3}}pe.mesh.rotation.y=Math.atan2(dx,dz);setAction(pe,'walk')}}pe.x=player.x;pe.z=player.z;pe.mesh.position.set(player.x,0,player.z);player.attackCd=Math.max(0,player.attackCd-dt);player.cooldowns=player.cooldowns.map(v=>Math.max(0,v-dt));player.mp=Math.min(player.maxMp,player.mp+player.maxMp*.022*dt);for(let e of state.entities)if(e.kind==='monster')updateMonster(e,dt);state.effects.forEach(f=>f.update(dt));state.effects=state.effects.filter(f=>!f.dead);state.mixers.forEach(m=>m.update(dt));let offset=new THREE.Vector3(14,17,16),desired=new THREE.Vector3(player.x,0,player.z).add(offset);camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(player.x,1,player.z);state.bossTimers.mini=Math.max(0,state.bossTimers.mini-dt);state.bossTimers.big=Math.max(0,state.bossTimers.big-dt);updateHUD()}
function updateMonster(e,dt){if(!e.alive){e.respawn-=dt;if(e.respawn<=0){e.alive=true;e.hp=e.maxHp;e.atk=e.baseAtk;e.phase=1;e.x=e.homeX;e.z=e.homeZ;e.mesh.position.set(e.x,0,e.z);e.mesh.visible=true;setAction(e,'idle');if(e.boss==='big'){toast('Печать древнего владыки разрушена…','rare');log('Регион: Хозяин Гнилого Леса пробудился.','combat')}}return}e.attackCd-=dt;for(let k in e.status)e.status[k]=Math.max(0,e.status[k]-dt);let dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz),safe=zoneAt(player.x,player.z).kind==='safe';if(!safe&&d<9){if(d>1.65){let sp=(e.boss?2.1:2.7)*(e.status.slow?0.45:1);e.x+=dx/d*sp*dt;e.z+=dz/d*sp*dt;e.mesh.position.set(e.x,0,e.z);e.mesh.rotation.y=Math.atan2(dx,dz);setAction(e,'walk')}else if(e.attackCd<=0){setAction(e,'attack',true);e.attackCd=e.boss?1.45:2.05;setTimeout(()=>{if(e.alive&&Math.hypot(player.x-e.x,player.z-e.z)<2.3)hurtPlayer(Math.max(1,Math.round(e.atk-player.stats.def*.2)))},280)}}else if(Math.hypot(e.x-e.homeX,e.z-e.homeZ)>7){e.x+=(e.homeX-e.x)*dt*.35;e.z+=(e.homeZ-e.z)*dt*.35;e.mesh.position.set(e.x,0,e.z);setAction(e,'walk')}else setAction(e,'idle');if(e.status.dot&&Math.random()<dt){damageMonster(e,Math.max(2,Math.round(player.stats.matk*.08)),false,false)}}
function worldToScreen(v){let p=v.clone().project(camera);return{x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight}}
function hurtPlayer(v){if(player.dead)return;player.hp-=v;damageNumber(state.playerEntity.mesh.position.clone().add(new THREE.Vector3(0,3,0)),`−${v}`,0xef6666);pulseScreen('#7c101a');if(player.hp<=0)die()}
function die(){player.dead=true;player.hp=0;state.paused=true;let loss=Math.floor(player.xp*.05);player.xp=Math.max(0,player.xp-loss);confirmBox('Вы пали',`Потеряно ${loss} опыта текущего уровня. Уровень и предметы сохранены.`,()=>{player.x=-7;player.z=-4;player.hp=player.maxHp;player.mp=player.maxMp;player.dead=false;state.playerEntity.mesh.visible=true;state.paused=false;closeConfirm();toast('Вы возродились в Гринфолле')},false)}
function basicAttack(){attackWith(null)}function castSkill(i){let s=CLASSES[player.classId].skills[i];if(player.cooldowns[i]>0)return toast('Навык ещё восстанавливается','bad');if(player.mp<s.cost)return toast(`Недостаточно: ${CLASSES[player.classId].resource}`,'bad');player.mp-=s.cost;player.cooldowns[i]=s.cd;attackWith(s)}
function attackWith(skill){let t=state.target;if(!t||!t.alive)return toast('Выберите живую цель','bad');let ranged=CLASSES[player.classId].ranged,range=ranged?12:2.6,d=Math.hypot(t.x-player.x,t.z-player.z);if(d>range){state.moveTarget={x:t.x+(player.x-t.x)/d*(ranged?8:1.6),z:t.z+(player.z-t.z)/d*(ranged?8:1.6)};return toast('Приближаемся к цели')}if(!skill&&player.attackCd>0)return;player.attackCd=1/(1+player.stats.dex*.035);state.moveTarget=null;state.playerEntity.mesh.rotation.y=Math.atan2(t.x-player.x,t.z-player.z);setAction(state.playerEntity,'attack',true);playSfx(skill?.fx||'attack');let magic=player.classId==='mage'||player.classId==='necro',base=magic?player.stats.matk:rand(player.stats.atkMin,player.stats.atkMax),mul=skill?.mul||1,crit=Math.random()<player.stats.crit/100,dmg=Math.max(1,Math.round(base*mul*(crit?1.75:1)));let delay=ranged?320:180;spawnAttackFx(skill?.fx||(ranged?'arrow':'slash'),state.playerEntity.mesh.position,t.mesh.position,()=>{let victims=[t];if(skill?.aoe)victims=state.entities.filter(e=>e.kind==='monster'&&e.alive&&Math.hypot(e.x-t.x,e.z-t.z)<skill.aoe);victims.forEach((e,k)=>damageMonster(e,Math.round(dmg*(k?0.72:1)),crit&&k===0));if(skill?.chain){state.entities.filter(e=>e.kind==='monster'&&e.alive&&e!==t).sort((a,b)=>Math.hypot(a.x-t.x,a.z-t.z)-Math.hypot(b.x-t.x,b.z-t.z)).slice(0,skill.chain-1).forEach(e=>{spawnAttackFx('lightning',t.mesh.position,e.mesh.position);damageMonster(e,Math.round(dmg*.68),false)})}if(skill?.dot)t.status.dot=skill.dot;if(skill?.slow)t.status.slow=skill.slow;if(skill?.stun)t.status.stun=skill.stun;if(skill?.leech)player.hp=Math.min(player.maxHp,player.hp+Math.round(dmg*skill.leech));if(skill?.summon)summonSkeleton()},delay)}
function damageMonster(e,dmg,crit=true,doFx=true){if(!e.alive)return;e.hp-=dmg;if(e.boss==='big'){let next=e.hp/e.maxHp<=.3?3:e.hp/e.maxHp<=.65?2:1;if(next>e.phase){e.phase=next;e.atk=Math.round(e.baseAtk*(1+(next-1)*.32));e.mesh.scale.multiplyScalar(1.08);impactFx(e.mesh.position,next===2?0x8bcf50:0xe74736);toast(next===2?'Владыка разрывает корни земли!':'Владыка входит в кровавую ярость!','rare');log(`Pit Boss: началась фаза ${next}.`,'combat');for(let i=0;i<next+1;i++){let a=i/(next+1)*Math.PI*2;spawnMonster(next===2?'wraith':'bat',e.x+Math.cos(a)*4,e.z+Math.sin(a)*4)}}}refreshNameplate(e);damageNumber(e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?6:3.3,0)),`${crit?'КРИТ ':''}−${dmg}`,crit?0xffd36b:0xf1e9da,crit);if(doFx)impactFx(e.mesh.position,e.tint);if(e.hp<=0)killMonster(e)}
function killMonster(e){e.alive=false;e.mesh.visible=false;setAction(e,'death',true);let d=MONSTERS[e.id];e.respawn=d.boss==='mini'?rand(180,300):d.boss==='big'?420:rand(28,48);if(d.boss)state.bossTimers[d.boss]=e.respawn;state.kills++;if(d.boss)state.bossKills++;gainXp(d.xp);let gold=rint(d.gold[0],d.gold[1]);player.gold+=gold;log(`${d.name} повержен: +${d.xp} опыта, +${gold} золота.`,'combat');for(let [id,ch] of d.drops)if(Math.random()<ch)addItem(id);if(state.target===e)state.target=null;if(state.quest===1&&state.kills>=8)state.quest=2;if(state.quest===2&&d.boss==='mini')state.quest=3;if(state.quest===3&&d.boss==='big')state.quest=4;updateQuest();saveGame()}
function gainXp(v){player.xp+=v;while(player.xp>=xpNeed()){player.xp-=xpNeed();player.level++;recalc(true);toast(`Достигнут уровень ${player.level}`,'rare');log(`Новый уровень: ${player.level}.`,'loot')}}
function addItem(id,count=1){let d=ITEMS[id],o=!d.slot&&player.inventory.find(x=>x.id===id);if(o)o.count+=count;else if(player.inventory.length<42)player.inventory.push(makeItem(id,0,count));else{state.lootBuffer.push(makeItem(id,0,count));toast('Сумка полна — добыча сохранена в буфере','bad');return}playSfx(d.rare?'rare':'loot');toast(`Получено: ${d.name}${count>1?' ×'+count:''}`,d.rare?'rare':'');log(`Получено: ${d.name}.`,'loot')}

function spawnAttackFx(type,from,to,onHit,delay=250){let a=from.clone().add(new THREE.Vector3(0,1.5,0)),b=to.clone().add(new THREE.Vector3(0,1.7,0));if(['fire','ice','arrow','bone','drain','curse','lightning','poison'].includes(type)){let color={fire:0xff5a20,ice:0x5ad7ff,arrow:0xe6d2a0,bone:0xe8e2c9,drain:0x52e4aa,curse:0xa64cff,lightning:0x8bdcff,poison:0x74dc50}[type],geo=new THREE.SphereGeometry(type==='arrow'?.1:.22,8,8),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:1}),m=new THREE.Mesh(geo,mat);m.position.copy(a);fxGroup.add(m);if(type!=='arrow'){let light=new THREE.PointLight(color,4,5);m.add(light)}let life=0,dur=delay/1000;state.effects.push({update(dt){life+=dt;m.position.lerpVectors(a,b,clamp(life/dur,0,1));m.scale.setScalar(1+Math.sin(life*30)*.25);if(life>=dur){this.dead=true;fxGroup.remove(m);onHit?.()}},dead:false})}else{let color=type==='guard'?0xe7bf6a:type==='shadow'?0xa847e9:0xffd38b,ring=new THREE.Mesh(new THREE.TorusGeometry(type==='impact'?.7:1.4,.09,8,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1}));ring.rotation.x=Math.PI/2;ring.position.copy(b);fxGroup.add(ring);let life=0;state.effects.push({update(dt){life+=dt;ring.scale.setScalar(1+life*2);ring.material.opacity=1-life/.5;if(life>.5){this.dead=true;fxGroup.remove(ring)}},dead:false});setTimeout(()=>onHit?.(),delay)}}
function impactFx(pos,color){for(let i=0;i<16;i++){let m=new THREE.Mesh(new THREE.SphereGeometry(.055,5,5),new THREE.MeshBasicMaterial({color}));m.position.copy(pos).add(new THREE.Vector3(0,1.2,0));let v=new THREE.Vector3(rand(-2.5,2.5),rand(.5,4),rand(-2.5,2.5));fxGroup.add(m);let life=0;state.effects.push({update(dt){life+=dt;v.y-=7*dt;m.position.addScaledVector(v,dt);m.material.opacity=1-life;m.material.transparent=true;if(life>1){this.dead=true;fxGroup.remove(m)}},dead:false})}}
function summonSkeleton(){let src=state.assets.monsters.Skeleton,obj=cloneAnimated(src,.006,0x55d8b0).root;obj.position.set(player.x+1,0,player.z+1);entityGroup.add(obj);let life=0;state.effects.push({update(dt){life+=dt;obj.rotation.y+=dt*.7;if(life>12){this.dead=true;entityGroup.remove(obj)}},dead:false});toast('Скелет будет сражаться 12 секунд')}
function pulseScreen(color){let el=$('.vignette');el.animate([{boxShadow:`inset 0 0 0 0 ${color}00`},{boxShadow:`inset 0 0 140px 30px ${color}aa`},{boxShadow:`inset 0 0 0 0 ${color}00`}],{duration:380})}
function initAudio(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();ambientGain=audioCtx.createGain();ambientGain.gain.value=state.settings.music*.018;ambientGain.connect(audioCtx.destination);let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=120;filter.connect(ambientGain);for(let [f,type] of [[47,'sawtooth'],[70,'sine']]){let o=audioCtx.createOscillator();o.type=type;o.frequency.value=f;o.connect(filter);o.start()}}
function playSfx(type){if(!audioCtx||!state.settings.sfx)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime,map={attack:[145,70,.1],slash:[210,90,.12],fire:[340,90,.28],ice:[760,320,.22],lightning:[940,150,.18],shadow:[180,55,.3],poison:[280,120,.2],drain:[110,360,.32],bone:[440,130,.15],arrow:[520,210,.1],loot:[660,880,.12],rare:[520,1040,.42]};let v=map[type]||map.attack;o.type=['fire','lightning','rare'].includes(type)?'sawtooth':'triangle';o.frequency.setValueAtTime(v[0],now);o.frequency.exponentialRampToValueAtTime(Math.max(30,v[1]),now+v[2]);g.gain.setValueAtTime(state.settings.sfx*.08,now);g.gain.exponentialRampToValueAtTime(.0001,now+v[2]);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+v[2])}
function damageNumber(pos,text,color,crit=false){if(!state.settings.damage)return;let p=worldToScreen(pos),e=document.createElement('div');e.className='damage-number '+(crit?'crit':'');e.style.cssText=`left:${p.x}px;top:${p.y}px;color:#${color.toString(16).padStart(6,'0')}`;e.textContent=text;$('#damage-layer').append(e);setTimeout(()=>e.remove(),1050)}

function updateHUD(){if(!state.started)return;let c=CLASSES[player.classId];$('#player-name').textContent=player.name;$('#player-class').textContent=`ур. ${player.level} · ${c.name}`;$('#portrait').textContent=c.skills[0].icon;$('#gold').textContent=player.gold.toLocaleString('ru-RU');setBar('hp',player.hp,player.maxHp);setBar('mp',player.mp,player.maxMp);$('#xp-fill').style.width=`${player.xp/xpNeed()*100}%`;$('#potion-count').textContent=countItem('potion');$('#ether-count').textContent=countItem('ether');let t=state.target,tf=$('#target-frame');if(t?.alive){tf.classList.remove('hidden');$('#target-name').textContent=t.name;$('#target-meta').textContent=`ур. ${t.level}`;$('#boss-mark').textContent=t.boss?t.boss==='big'?'PIT BOSS':'MINI RAID':'';$('#target-fill').style.width=`${t.hp/t.maxHp*100}%`;$('#target-hp').textContent=`${Math.max(0,Math.ceil(t.hp)).toLocaleString()} / ${t.maxHp.toLocaleString()}`}else tf.classList.add('hidden');$$('[data-skill]').forEach((b,i)=>b.querySelector('.cooldown').textContent=player.cooldowns[i]>0?player.cooldowns[i].toFixed(1):'');let z=zoneAt(player.x,player.z);$('#zone').textContent=z.name;let hour=Math.floor(state.worldTime),min=Math.floor((state.worldTime-hour)*60);$('#clock').textContent=`${String(hour).padStart(2,'0')}:${String(min).padStart(2,'0')}`;$('#mini-timer').textContent=state.bossTimers.mini?fmtTime(state.bossTimers.mini):'жив';$('#big-timer').textContent=state.bossTimers.big?fmtTime(state.bossTimers.big):'жив';drawMinimap()}
function setBar(id,v,max){$(`#${id}-fill`).style.width=`${clamp(v/max*100,0,100)}%`;$(`#${id}-text`).textContent=`${Math.max(0,Math.ceil(v))} / ${max}`}
function fmtTime(s){return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function drawMinimap(){let c=$('#minimap'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);let g=x.createRadialGradient(214,164,20,214,164,260);g.addColorStop(0,'#263630');g.addColorStop(1,'#090f11');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#746248';x.lineWidth=8;x.beginPath();x.moveTo(40,270);x.bezierCurveTo(120,220,200,190,380,50);x.stroke();for(let l of LOCATIONS){let px=(l.x+50)/100*c.width,pz=(l.z+42)/84*c.height;x.fillStyle=l.kind==='safe'?'#d6ad61':'#7d4038';x.beginPath();x.arc(px,pz,l.kind==='safe'?8:5,0,7);x.fill()}x.fillStyle='#fff3bd';x.beginPath();x.arc((player.x+50)/100*c.width,(player.z+42)/84*c.height,5,0,7);x.fill();x.strokeStyle='#d2ad69';x.strokeRect(1,1,c.width-2,c.height-2)}
function log(text,type='system'){let m=$('#messages');m.insertAdjacentHTML('beforeend',`<div class="msg-${type}">${text}</div>`);while(m.children.length>8)m.firstElementChild.remove()}
function toast(text,type=''){let e=document.createElement('div');e.className=`toast ${type}`;e.textContent=text;$('#notices').append(e);setTimeout(()=>e.remove(),3800)}
function updateQuest(){let data=[['Голос границы','Поговорите со старостой Гринфолла.',0],['Кровь на дороге',`Победите тварей рубежа: ${Math.min(state.kills,8)} / 8`,state.kills/8],['Вой стаи','Отыщите Кровавого Оборотня в Чёрном лесу.',.2],['Печать владыки','Спуститесь к шахте и победите Хозяина Гнилого Леса.',.55],['Первый след','Вертикальный срез пройден. Продолжайте охоту и заточку.',1]][state.quest]||[];$('#quest-title').textContent=data[0];$('#quest-text').textContent=data[1];$('#quest-progress').style.width=`${clamp(data[2],0,1)*100}%`}

const keys={};addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;keys[e.key.toLowerCase()]=true;if(!state.started)return;if(['1','2','3','4'].includes(e.key))castSkill(+e.key-1);if(e.code==='Space'){e.preventDefault();basicAttack()}let k=e.key.toLowerCase();if(k==='i')openWindow('inventory');if(k==='c')openWindow('character');if(k==='k')openWindow('skills');if(k==='m')openWindow('map');if(k==='q')useItem('potion');if(k==='e')useItem('ether');if(e.key==='Escape')openWindow('settings');if(e.key==='Enter')$('#chat').focus()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointerdown',e=>{if(!state.started||state.paused)return;pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(pointer,camera);let entityHits=raycaster.intersectObjects(entityGroup.children,true);if(entityHits.length){let o=entityHits[0].object;while(o&&!o.userData.entity)o=o.parent;let ent=o?.userData.entity;if(ent){if(ent.kind==='monster'){state.target=ent;state.moveTarget=null;return}if(ent.kind==='npc'&&Math.hypot(ent.x-player.x,ent.z-player.z)<3.2){interactNPC(ent);return}}}let hits=raycaster.intersectObject(ground);if(hits.length){state.moveTarget={x:hits[0].point.x,z:hits[0].point.z};state.target=null}});
function interactNPC(n){if(n.role==='elder'){state.quest=Math.max(1,state.quest);updateQuest();openDialog(n,'За стенами снова слышен вой. Восемь тварей — и я поверю, что ты способен пережить эту ночь.',[{label:'Я очищу дорогу',action:closeWindow}])}if(n.role==='shop')openShop(n);if(n.role==='smith')openForge(n);if(n.role==='teleport')openTeleport(n)}

function openWindow(type){if(!state.started)return;state.paused=true;$('#modal-root').innerHTML='<div class="modal-shade"></div><section class="window"><button class="close-window">×</button><div id="window-content"></div></section>';$('.close-window').onclick=closeWindow;$('.modal-shade').onclick=closeWindow;if(type==='inventory')renderInventory();if(type==='character')renderCharacter();if(type==='skills')renderSkills();if(type==='map')renderMap();if(type==='settings')renderSettings();$$('[data-window]').forEach(b=>b.classList.toggle('active',b.dataset.window===type))}
function closeWindow(){state.paused=false;$('#modal-root').innerHTML='';$$('[data-window]').forEach(b=>b.classList.remove('active'));canvas.focus()}
function tabs(active){return`<div class="tabs">${[['character','Персонаж'],['inventory','Инвентарь'],['skills','Навыки'],['map','Карта'],['settings','Настройки']].map(([id,n])=>`<button class="tab ${active===id?'active':''}" data-goto="${id}">${n}</button>`).join('')}</div>`}function bindTabs(){$$('[data-goto]').forEach(b=>b.onclick=()=>openWindow(b.dataset.goto))}
function formatItem(o){let d=itemDef(o);return`<span><span class="big-icon">${d.icon}${o.plus?' <small>+'+o.plus+'</small>':''}</span>${d.name}</span>${o.count>1?`<span class="count">${o.count}</span>`:''}`}
function renderInventory(sel=state.selectedItem){let w=$('#window-content');w.innerHTML=`<h2>Инвентарь</h2>${tabs('inventory')}<div class="inventory-layout"><div class="doll"><div class="doll-art"></div>${EQUIP_SLOTS.map(s=>`<button class="equip-slot ${player.equipment[s]?'filled':''}" data-equip="${s}" data-slot="${s}">${player.equipment[s]?formatItem(player.equipment[s]):SLOT_NAMES[s]}</button>`).join('')}</div><div><div class="bag-head"><b>Сумка</b><span>${player.inventory.length} / 42 · ◈ ${player.gold.toLocaleString()} ${state.lootBuffer.length?`· Буфер: ${state.lootBuffer.length} <button class="dark-btn" id="collect-buffer">Забрать</button>`:''}</span></div><div class="bag-grid">${player.inventory.map((o,i)=>`<button class="item-card ${i===sel?'selected':''} ${itemDef(o).rare?'rare':''}" data-item="${i}">${formatItem(o)}</button>`).join('')}${Array(Math.max(0,42-player.inventory.length)).fill('<div class="item-card"></div>').join('')}</div><div class="item-details" id="item-details">Выберите предмет. Все вещи можно надевать с любого уровня.</div></div></div>`;bindTabs();$$('[data-item]').forEach(b=>b.onclick=()=>selectItem(+b.dataset.item));$$('[data-equip]').forEach(b=>b.onclick=()=>unequip(b.dataset.equip));if($('#collect-buffer'))$('#collect-buffer').onclick=()=>{while(state.lootBuffer.length&&player.inventory.length<42)player.inventory.push(state.lootBuffer.shift());renderInventory();saveGame()}}
function selectItem(i){state.selectedItem=i;renderInventory(i);let o=player.inventory[i],d=itemDef(o),parts=[],slot=d.slot==='ring'?'ring1':d.slot,current=slot&&player.equipment[slot];if(d.atk)parts.push(`Урон ${d.atk[0]}–${d.atk[1]}`);if(d.matk)parts.push(`Магическая атака +${d.matk}`);if(d.def)parts.push(`Защита +${d.def}`);if(d.mdef)parts.push(`Магическая защита +${d.mdef}`);let compare=d.slot?`<br><span style="color:#c4a876">Надето: ${current?itemDef(current).name+(current.plus?' +'+current.plus:''):'ничего'}</span>`:'';$('#item-details').innerHTML=`<b>${d.name}${o.plus?' +'+o.plus:''}</b><br>${parts.join(' · ')||d.desc||'Ресурс мира'}${compare}<br><span style="color:#8f887c">Источник: ${d.origin||'Торговцы Варендора'}</span><div class="action-row">${d.slot?'<button class="gold-btn" id="equip-item">Надеть</button>':''}${d.type==='consumable'?'<button class="gold-btn" id="use-item">Использовать</button>':''}<button class="dark-btn" id="sell-item">Продать за ${Math.floor(d.value*.48)} ◈</button></div>`;if($('#equip-item'))$('#equip-item').onclick=()=>equipItem(i);if($('#use-item'))$('#use-item').onclick=()=>{useItem(o.id);renderInventory()};$('#sell-item').onclick=()=>sellItem(i)}
function equipItem(i){let o=player.inventory[i],d=itemDef(o),slot=d.slot;if(slot==='ring')slot=!player.equipment.ring1?'ring1':'ring2';if(player.equipment[slot])player.inventory.push(player.equipment[slot]);player.equipment[slot]=o;player.inventory.splice(i,1);state.selectedItem=null;recalc();renderInventory();toast(`Надето: ${d.name}`);saveGame()}
function unequip(slot){let o=player.equipment[slot];if(!o||player.inventory.length>=42)return;player.inventory.push(o);delete player.equipment[slot];recalc();renderInventory();saveGame()}
function sellItem(i){let o=player.inventory[i],d=itemDef(o);player.gold+=Math.floor(d.value*.48)*o.count;player.inventory.splice(i,1);state.selectedItem=null;renderInventory();updateHUD();saveGame()}
function renderCharacter(){let s=player.stats,c=CLASSES[player.classId],rows=[['Уровень',player.level],['Опыт',`${player.xp.toLocaleString()} / ${xpNeed().toLocaleString()}`],['Сила',s.str],['Ловкость',s.dex],['Интеллект',s.int],['Выносливость',s.vit],['Дух',s.spi],['Физическая атака',`${Math.floor(s.atkMin)}–${Math.floor(s.atkMax)}`],['Магическая атака',Math.floor(s.matk)],['Физическая защита',Math.floor(s.def)],['Магическая защита',Math.floor(s.mdef)],['Критический шанс',s.crit.toFixed(1)+'%'],['Точность',s.accuracy.toFixed(1)],['Уклонение',s.evasion.toFixed(1)],['Скорость движения',s.speed.toFixed(1)],['Побеждено боссов',state.bossKills]];$('#window-content').innerHTML=`<h2>${player.name} · ${c.name}</h2>${tabs('character')}<div class="stat-columns"><section><h3>Основные параметры</h3>${rows.slice(0,8).map(r=>`<div class="stat-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}</section><section><h3>Боевые параметры</h3>${rows.slice(8).map(r=>`<div class="stat-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}</section></div><p style="color:#9c9488;margin-top:22px">Экипировка не имеет требований уровня. Её ценность определяется источником, фиксированными характеристиками и рисковой заточкой.</p><button class="danger-btn" id="reset-save">Удалить персонажа</button>`;bindTabs();$('#reset-save').onclick=()=>confirmBox('Удалить персонажа?', 'Весь локальный прогресс будет удалён без восстановления.',()=>{localStorage.removeItem(SAVE_KEY);location.reload()})}
function renderSkills(){let c=CLASSES[player.classId];$('#window-content').innerHTML=`<h2>Навыки · ${c.name}</h2>${tabs('skills')}<div class="skill-tree">${c.skills.map((s,i)=>`<div class="skill-node"><div class="node-icon">${s.icon}</div><div><b>${i+1}. ${s.name}</b><p>Расход: ${s.cost} ${c.resource.toLowerCase()} · Перезарядка: ${s.cd} сек.</p><span>${s.mul?`Сила: ${Math.round(s.mul*100)}%`:'Тактический эффект'}${s.aoe?' · Область '+s.aoe+' м':''}${s.dot?' · Урон со временем':''}</span></div></div>`).join('')}</div>`;bindTabs()}
function renderMap(){$('#window-content').innerHTML=`<h2>Карта Варендора</h2>${tabs('map')}<div class="map-large"><div class="map-road" style="left:11%;top:68%;width:75%;transform:rotate(-27deg)"></div>${LOCATIONS.map((l,i)=>`<button class="map-node" style="left:${12+i*19}%;top:${76-i*13}%"><b>${l.name}</b><small>${l.level}</small><br><span>${l.desc}</span></button>`).join('')}</div>`;bindTabs()}
function renderSettings(){let s=state.settings;$('#window-content').innerHTML=`<h2>Настройки</h2>${tabs('settings')}<div class="settings-grid"><section><h3>Графика</h3><div class="setting"><label>Качество<select id="quality"><option value="low">Низкое</option><option value="medium">Среднее</option><option value="high">Высокое</option><option value="ultra">Ультра</option></select></label></div><div class="setting"><label>Динамические тени <input type="checkbox" id="shadows" ${s.shadows?'checked':''}></label></div><div class="setting"><label>Свечение и магические эффекты <input type="checkbox" id="bloom" ${s.bloom?'checked':''}></label></div><div class="setting"><label>Цифры урона <input type="checkbox" id="damage" ${s.damage?'checked':''}></label></div><div class="setting"><label>Дрожание камеры <input type="checkbox" id="shake" ${s.screenShake?'checked':''}></label></div></section><section><h3>Звук и интерфейс</h3>${[['music','Музыка'],['sfx','Эффекты'],['ui','Интерфейс']].map(([id,n])=>`<div class="setting"><label>${n}<b id="${id}-value">${Math.round(s[id]*100)}%</b></label><input type="range" min="0" max="100" value="${s[id]*100}" data-volume="${id}"></div>`).join('')}<h3>Управление</h3><div class="stat-row"><span>Движение</span><b>ЛКМ / WASD</b></div><div class="stat-row"><span>Обычная атака</span><b>Space</b></div><div class="stat-row"><span>Навыки</span><b>1–4</b></div><button class="gold-btn" id="save-settings">Применить</button></section></div>`;bindTabs();$('#quality').value=s.quality;$$('[data-volume]').forEach(i=>i.oninput=()=>$('#'+i.dataset.volume+'-value').textContent=i.value+'%');$('#save-settings').onclick=()=>{s.quality=$('#quality').value;s.shadows=$('#shadows').checked;s.bloom=$('#bloom').checked;s.damage=$('#damage').checked;s.screenShake=$('#shake').checked;$$('[data-volume]').forEach(i=>s[i.dataset.volume]=+i.value/100);applySettings();saveGame();toast('Настройки применены');closeWindow()}}
function applySettings(){let s=state.settings,ratio={low:.75,medium:1,high:1.45,ultra:Math.min(devicePixelRatio,2)}[s.quality];renderer.setPixelRatio(ratio);renderer.shadowMap.enabled=s.shadows;moon.castShadow=s.shadows;bloom.enabled=s.bloom;if(ambientGain)ambientGain.gain.value=s.music*.018}
function openDialog(n,text,actions){openWindow('character');$('#window-content').innerHTML=`<h2>${n.name}</h2><div class="npc-dialog"><div class="npc-portrait"></div><div><div class="eyebrow">Гринфолл</div><h3>${n.name}</h3><p style="font:20px/1.6 'Cormorant Garamond'">«${text}»</p><div class="action-row">${actions.map((a,i)=>`<button class="${i?'dark-btn':'gold-btn'}" data-dialog="${i}">${a.label}</button>`).join('')}</div></div></div>`;$$('[data-dialog]').forEach(b=>b.onclick=actions[+b.dataset.dialog].action)}
function openShop(n){openWindow('character');let stock=[['potion',55],['ether',70],['scroll',240],['teleport',130]];$('#window-content').innerHTML=`<h2>Лавка Эльзы</h2><div class="npc-dialog"><div class="npc-portrait"></div><div><p>Редкие вещи не продаются. За ними придётся идти в лес.</p><div class="shop-grid">${stock.map(([id,c])=>`<div class="shop-item"><span class="big-icon">${ITEMS[id].icon}</span><b>${ITEMS[id].name}</b><span>◈ ${c}</span><button class="dark-btn" data-buy="${id}" data-cost="${c}">Купить</button></div>`).join('')}</div></div></div>`;$$('[data-buy]').forEach(b=>b.onclick=()=>{let cost=+b.dataset.cost;if(player.gold<cost)return toast('Недостаточно золота','bad');player.gold-=cost;addItem(b.dataset.buy);updateHUD()})}
function openTeleport(n){openWindow('character');let points=[['Астерхолд',-27,-19,0,1],['Гринфолл',-7,-4,25,1],['Чёрный лес',21,9,90,10],['Вход в шахту',35,27,150,10]];$('#window-content').innerHTML=`<h2>Проводник Каэль</h2><p>Путь сохраняет цену. Бесплатен только переход в столицу. Чёрный лес открывается на 10 уровне.</p><div class="shop-grid">${points.map(p=>`<div class="shop-item"><b>${p[0]}</b><span>◈ ${p[3]} · ур. ${p[4]}</span><button class="dark-btn" data-tp="${p.slice(1).join(',')}">Отправиться</button></div>`).join('')}</div>`;$$('[data-tp]').forEach(b=>b.onclick=()=>{let [x,z,c,level]=b.dataset.tp.split(',').map(Number);if(player.level<level)return toast(`Требуется доступ к территории: уровень ${level}`,'bad');if(player.gold<c)return toast('Недостаточно золота','bad');player.gold-=c;player.x=x;player.z=z;state.moveTarget=null;closeWindow();toast('Переход завершён')})}
function openForge(n){openWindow('character');renderForge()}
function renderForge(){let gear=Object.entries(player.equipment).filter(([,o])=>o);$('#window-content').innerHTML=`<h2>Кузница Брана</h2><p>Усиление до +3 безопасно. Начиная с попытки <b>+3 → +4</b>, неудача полностью уничтожает предмет.</p><p>Свитков: <b>${countItem('scroll')}</b></p><div class="bag-grid">${gear.map(([slot,o])=>`<button class="item-card ${itemDef(o).rare?'rare':''}" data-forge="${slot}">${formatItem(o)}</button>`).join('')}</div><div class="item-details" id="forge-info">Выберите надетый предмет.</div>`;$$('[data-forge]').forEach(b=>b.onclick=()=>{let o=player.equipment[b.dataset.forge],ch=ENHANCE[o.plus]||0;$('#forge-info').innerHTML=`<b>${itemDef(o).name} +${o.plus} → +${o.plus+1}</b><br>Вероятность успеха: ${Math.round(ch*100)}%. ${o.plus>=3?'<span class="danger-text">При неудаче предмет будет уничтожен.</span>':'Безопасное улучшение.'}<div class="action-row"><button class="gold-btn" id="enhance">Усилить</button></div>`;$('#enhance').onclick=()=>attemptEnhance(b.dataset.forge)})}
function attemptEnhance(slot){let o=player.equipment[slot];if(!o||o.plus>=15)return;if(!countItem('scroll'))return toast('Нужен свиток улучшения','bad');let run=()=>{consumeItem('scroll');if(Math.random()<ENHANCE[o.plus]){o.plus++;recalc();toast(`${itemDef(o).name} усилен до +${o.plus}`,o.plus>=7?'rare':'');log(`Заточка успешна: ${itemDef(o).name} +${o.plus}.`,'loot')}else{let name=itemDef(o).name;delete player.equipment[slot];recalc();toast(`${name} уничтожен`,'bad');log(`Неудача: ${name} уничтожен при заточке.`,'combat')}closeConfirm();renderForge();saveGame()};if(o.plus>=3)confirmBox('Рискованная заточка',`Шанс успеха ${Math.round(ENHANCE[o.plus]*100)}%. <span class="danger-text">При неудаче предмет будет уничтожен.</span> Продолжить?`,run);else run()}
function countItem(id){return player.inventory.filter(o=>o.id===id).reduce((a,o)=>a+o.count,0)}function consumeItem(id){let i=player.inventory.findIndex(o=>o.id===id);if(i<0)return false;if(--player.inventory[i].count<=0)player.inventory.splice(i,1);return true}
function useItem(id){if(id==='potion'){if(player.hp>=player.maxHp)return toast('Здоровье уже полное');if(!consumeItem(id))return toast('Нет багровых зелий','bad');player.hp=Math.min(player.maxHp,player.hp+Math.round(player.maxHp*.45));toast('Здоровье восстановлено')}else if(id==='ether'){if(player.mp>=player.maxMp)return toast('Ресурс уже полный');if(!consumeItem(id))return toast('Нет эфирных зелий','bad');player.mp=Math.min(player.maxMp,player.mp+Math.round(player.maxMp*.45));toast(`${CLASSES[player.classId].resource} восстановлена`)}else if(id==='teleport'){if(consumeItem(id)){player.x=-7;player.z=-4;toast('Камень возвращает вас в Гринфолл')}}updateHUD();saveGame()}
function confirmBox(title,text,yes,cancel=true){state.paused=true;$('#confirm-root').innerHTML=`<div class="modal-shade"></div><div class="confirm-box glass"><h3>${title}</h3><p>${text}</p><div class="action-row" style="justify-content:center"><button class="gold-btn" id="confirm-yes">Продолжить</button>${cancel?'<button class="dark-btn" id="confirm-no">Отмена</button>':''}</div></div>`;$('#confirm-yes').onclick=yes;if(cancel)$('#confirm-no').onclick=closeConfirm}function closeConfirm(){state.paused=false;$('#confirm-root').innerHTML=''}
function saveGame(){if(!state.started)return;localStorage.setItem(SAVE_KEY,JSON.stringify({player,quest:state.quest,kills:state.kills,bossKills:state.bossKills,lootBuffer:state.lootBuffer,settings:state.settings}))}
$$('[data-window]').forEach(b=>b.onclick=()=>openWindow(b.dataset.window));$('#potion').onclick=()=>useItem('potion');$('#ether').onclick=()=>useItem('ether');function sendChat(){let i=$('#chat');if(i.value.trim())log(`[Общий] ${player.name}: ${i.value.trim()}`);i.value='';i.blur();canvas.focus()}$('#send-chat').onclick=sendChat;$('#chat').onkeydown=e=>{if(e.key==='Enter')sendChat()};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});
let saveTimer=0;function loop(){requestAnimationFrame(loop);let dt=Math.min(clock3.getDelta(),.04);if(state.started){if(!state.paused){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dz){let d=Math.hypot(dx,dz);state.moveTarget={x:player.x+dx/d*2,z:player.z+dz/d*2}}update(dt);saveTimer+=dt;if(saveTimer>8){saveGame();saveTimer=0}}}if(state.settings.bloom)composer.render();else renderer.render(scene,camera)}loop();
